### ISSUE TITLE
Formats as a package

### ISSUE THREAD

**Issue by rkgrep** [joomla-framework/registry#21]
In addtition to this pull: https://github.com/joomla-framework/registry/pull/7 I propose separating registry formats to an independent package as they create stdClass instances from strings (and vice versa) but not Registry instances directly.
This will make them more flexible and there will be a chance to implement new options and formats used  not only by the Registry class.

**Comment by mbabker** [comment]
Not going through with this.  Having worked with other loader/parser packages, they're really tied to the data structure they work with and I don't see us making the format classes usable as something truly standalone.
