### ISSUE TITLE
3rd argument for get() function

### ISSUE THREAD

**Issue by C-Lodder** [joomla-framework/registry#47]
May be pointless but would it be possible to add a 3rd argument ($cast) for the `get()` function, just like there is for `JInput`?

```
public function get($path, $default = null, $cast = null)
{
}
```

Meaning that for example when we get parameters, like so:

```
$params->get('number', 1)
```

We don't need to manually cast to an integer/bool/string (or whatever it may be) if we want to perform strict comparisons.

**Now:**

```
$number = (int) $params->get('number', 1);

if (1 === $number)
{
}
```

**After:**

```
$number = $params->get('number', 1, 'INT');

if (1 === $number)
{
}
```

**Comment by mbabker** [comment]
I wouldn't do that here.

In the Input package, the data is being read out of the request and it's all coming into PHP as strings from the web server.  The Input package is doing a mix of filtering the request data and casting it depending on the type of filter in use.  For the Registry, developers have to put the data into it on their own so they are getting back exactly what they put in.

What's tricky is that in the CMS the Registry is commonly used for things like form parameters, and unfortunately that data isn't always being filtered/casted appropriately in the form API before it gets saved, so everything is defaulting back to strings.

Using the same logic in https://github.com/joomla/joomla-cms/pull/17082 you should be able to have the API typecast the form data when it is processed and that should help with ensuring everything is type safe.

**Comment by C-Lodder** [comment]
Ah fair enough, so if I add `filter="input"` to the field, am I guaranteed an integer?

**Comment by mbabker** [comment]
Well, `filter="integer"`, but yes when you do that the data array will give you an appropriately filtered/casted value.

Step through https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Form.php#L1249 basically.  JForm itself has some "special" filter values that it supports, then it will fall back to trying to use a custom filter function you define, then use one of the filters in https://github.com/joomla-framework/filter/blob/2.0-dev/src/InputFilter.php#L209 if no other case matches.

**Comment by C-Lodder** [comment]
Ok cheers Babker, will have a sift through that function properly later on.
