### ISSUE TITLE
Deprecated version 3 or 4

### ISSUE THREAD

**Issue by brianteeman** [joomla-framework/registry#72]
which is it v3 or v4?

https://github.com/joomla-framework/registry/blob/299ea7651f402ddcc6f50308c98a2057e05f1856/src/Registry.php#L460-L470

**Comment by HLeithner** [comment]
I think 4, 3 would be in joomla 5 and that's a bit too early @Fedik ?

**Comment by Fedik** [comment]
Yes it for 4.

> a bit too early

I cannot say. Will keep 4, it can be extended anytime anyway.

**Comment by brianteeman** [comment]
see #73
