### ISSUE TITLE
Instances being converted into stdClass

### ISSUE THREAD

**Issue by bweston92** [joomla-framework/registry#8]
Instances being converted into stdClass.

```
/** @var \JTable $message */
$registry = new Joomla\Registry\Registry(compact('message'));
```

Expected:
```
$registry->get('message') instanceof HelloTableMessage
```

Got
```
$registry->get('message') instanceof stdClass
```

**Comment by mbabker** [comment]
Can't reproduce.  Also added a unit test case validating not only that a class instance is returned but the same one that is set is also retrieved.
